x=input('Enter a number ')
y=input('Enter a number ')
print('the type of x is',type(x))
x=int(x)
y=int(y)
print('the type of x after type convrsn is',type(x))
print('The sum is',x+y)
print('the pdt is',x*y)
print('The diff is',x-y)
print('the div rounded off is',x//y)
print('the power fn is',x**y)
print('the remainder of x/y is',x%y)
print('the div is',x/y)